"""Overturo SDK — the trust conductor.

Backend SDK unifying the OAP authorize protocol (relying-party side)
and the Oversight Mode SDK (issuer / attester side).


NOTE: Phase H expands this surface to the full flat re-export set
(adds the oversight + decisions namespaces). This Phase E version
exposes the authorize-side public symbols plus the cross-cutting
errors / models / verify so the relocated tests pass.
"""

__version__ = "1.0.0"

from . import decisions, receipts
from .authorize import (
    DpopKeyPair,
    OverturoAuthorize,
    OverturoChronicleStream,
    OverturoDecisionAdapter,
    access_token_hash,
    jwk_thumbprint,
    peek_receipt,
    sign_dpop_proof,
)
from .errors import (
    OapApprovalRequired,
    OapAuthorizationDenied,
    OapDispatchError,
    OapError,
    OapEscalationDenied,
    OapIntentDenied,
    OapSequenceDenied,
    OapTrajectoryDenied,
    OapWrongRegion,
    OverturoApiError,
    OverturoConfigError,
    OverturoError,
    OverturoNetworkError,
    OverturoRateLimited,
    OverturoServerError,
    OverturoTimeoutError,
    OverturoUnauthorized,
    OverturoValidationError,
    ReceiptInvalid,
    RecordInvalid,
    is_oap_error,
)
from .models import (
    AttestResult,
    DecisionKind,
    DecisionMode,
    DecisionStatus,
    DecisionStatusLiteral,
    DecisionToken,
    EscalateResult,
    Escalation,
    FlowDisclosures,
    JwksKey,
    OfflineVerifyResult,
    OverturoBlockInvocation,
    OverturoDecision,
    OverturoDecisionMalformed,
    OverturoEscalation,
    OverturoReceipt,
    PeekedReceipt,
    RevokeResult,
    TokenInfo,
    VerifiedReceipt,
    parse_decision,
)
from .oversight import (
    ISS_ROLE_TO_TRUST_WEIGHT,
    ISS_ROLES,
    Decision,
    Discovery,
    IssRole,
    LegalBasis,
    LogLevel,
    OversightConfig,
    OverturoOversight,
    ResolvedEndpoints,
    RevocationReason,
    RevocationScope,
    TrustWeight,
    evidence_digest,
)
from .records import (
    VerifiedRecord,
    canonical_bytes,
    manifest_content_hash,
    verify_manifest_pin,
    verify_record,
)
from .verify import (
    JwksCache,
    raw_ed25519_to_jwk,
    verify_receipt,
    verify_receipt_offline,
)

# Explicit public surface. Listing every re-export here makes the
# import block clearly intentional to ruff (F401) and to readers,
# and pins the SDK's API contract — anything not listed is internal
# regardless of how it's imported.
__all__ = [
    "ISS_ROLES",
    "ISS_ROLE_TO_TRUST_WEIGHT",
    "AttestResult",
    "Decision",
    "DecisionKind",
    "DecisionMode",
    "DecisionStatus",
    "DecisionStatusLiteral",
    "DecisionToken",
    "Discovery",
    "DpopKeyPair",
    "EscalateResult",
    "Escalation",
    "FlowDisclosures",
    "IssRole",
    "JwksCache",
    "JwksKey",
    "LegalBasis",
    "LogLevel",
    "OapApprovalRequired",
    "OapAuthorizationDenied",
    "OapDispatchError",
    "OapError",
    "OapEscalationDenied",
    "OapIntentDenied",
    "OapSequenceDenied",
    "OapTrajectoryDenied",
    "OapWrongRegion",
    "OfflineVerifyResult",
    "OversightConfig",
    "OverturoApiError",
    "OverturoAuthorize",
    "OverturoBlockInvocation",
    "OverturoChronicleStream",
    "OverturoConfigError",
    "OverturoDecision",
    "OverturoDecisionAdapter",
    "OverturoDecisionMalformed",
    "OverturoError",
    "OverturoEscalation",
    "OverturoNetworkError",
    "OverturoOversight",
    "OverturoRateLimited",
    "OverturoReceipt",
    "OverturoServerError",
    "OverturoTimeoutError",
    "OverturoUnauthorized",
    "OverturoValidationError",
    "PeekedReceipt",
    "ReceiptInvalid",
    "RecordInvalid",
    "ResolvedEndpoints",
    "RevocationReason",
    "RevocationScope",
    "RevokeResult",
    "TokenInfo",
    "TrustWeight",
    "VerifiedReceipt",
    "VerifiedRecord",
    "__version__",
    "access_token_hash",
    "canonical_bytes",
    "decisions",
    "evidence_digest",
    "manifest_content_hash",
    "is_oap_error",
    "jwk_thumbprint",
    "parse_decision",
    "peek_receipt",
    "raw_ed25519_to_jwk",
    "receipts",
    "sign_dpop_proof",
    "verify_manifest_pin",
    "verify_receipt",
    "verify_receipt_offline",
    "verify_record",
]
